const fs = require("fs");
const path = require("path");

function loadEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    return {};
  }

  const env = {};

  fs.readFileSync(filePath, "utf8").split("\n").forEach((line) => {
    const trimmed = line.trim();

    if (!trimmed || trimmed.startsWith("#")) {
      return;
    }

    const separatorIndex = trimmed.indexOf("=");

    if (separatorIndex === -1) {
      return;
    }

    const key = trimmed.slice(0, separatorIndex);
    let value = trimmed.slice(separatorIndex + 1);

    if (
      (value.startsWith("\"") && value.endsWith("\"")) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    env[key] = value;
  });

  return env;
}

const rootDir = path.join(__dirname, "..");
const fileEnv = {
  ...loadEnvFile(path.join(rootDir, ".env")),
  ...loadEnvFile(path.join(rootDir, ".env.local"))
};

function getEnv(key) {
  return process.env[key] || fileEnv[key] || "";
}

const projectId = getEnv("VITE_FIREBASE_PROJECT_ID");

const firebaseConfig = {
  apiKey: getEnv("VITE_FIREBASE_API_KEY"),
  authDomain: getEnv("VITE_FIREBASE_AUTH_DOMAIN"),
  projectId,
  storageBucket: getEnv("VITE_FIREBASE_STORAGE_BUCKET") || (projectId ? `${projectId}.firebasestorage.app` : ""),
  messagingSenderId: getEnv("VITE_FIREBASE_MESSAGING_SENDER_ID"),
  appId: getEnv("VITE_FIREBASE_APP_ID")
};

const mapboxToken = getEnv("VITE_MAPBOX_TOKEN");

const requiredKeys = [
  "VITE_FIREBASE_API_KEY",
  "VITE_FIREBASE_AUTH_DOMAIN",
  "VITE_FIREBASE_PROJECT_ID",
  "VITE_FIREBASE_MESSAGING_SENDER_ID",
  "VITE_FIREBASE_APP_ID",
  "VITE_MAPBOX_TOKEN"
];

const missingKeys = requiredKeys.filter((key) => !getEnv(key));

if (missingKeys.length) {
  console.warn(`Warning: missing env vars: ${missingKeys.join(", ")}`);
}

const output = `// Auto-generated by scripts/generate-config.js — do not edit
export const firebaseConfig = ${JSON.stringify(firebaseConfig, null, 2)};
export const mapboxToken = ${JSON.stringify(mapboxToken)};
`;

fs.writeFileSync(path.join(rootDir, "js", "config.js"), output);
console.log("Generated js/config.js");
